import { AbilityConstant, UIAbility, Want } from '@kit.AbilityKit';
import { hilog } from '@kit.PerformanceAnalysisKit';
import { window } from '@kit.ArkUI';
import Global from '../manager/Global';

export default class EntryAbility extends UIAbility {
  onCreate(want: Want, launchParam: AbilityConstant.LaunchParam): void {
    hilog.info(0x0000, 'testTag', '%{public}s', 'Ability onCreate');
    Global.getContext().context = this.context;
    Global.getContext().init();
  }

  onDestroy(): void {
    hilog.info(0x0000, 'testTag', '%{public}s', 'Ability onDestroy');
  }

  onWindowStageCreate(windowStage: window.WindowStage): void {
    // Main window is created, set main page for this ability
    hilog.info(0x0000, 'testTag', '%{public}s', 'Ability onWindowStageCreate');

    windowStage.loadContent('pages/Splash', (err) => {
      if (err.code) {
        hilog.error(0x0000, 'testTag', 'Failed to load the content. Cause: %{public}s', JSON.stringify(err) ?? '');
        return;
      }
      hilog.info(0x0000, 'testTag', 'Succeeded in loading the content.');

      // 设置成全屏
      windowStage.getMainWindow((err, windowClass) => {
        windowClass.setWindowLayoutFullScreen(true)
        windowClass.setWindowSystemBarEnable(['navigation'])
        windowClass.setWindowBackgroundColor('#00000000');
        windowClass.setWindowBackgroundColor('#00000000');
        let SystemBarProperties: window.SystemBarProperties = {
          statusBarColor: '#000000',
          navigationBarColor: '#000000',
          //以下两个属性从API Version8开始支持
          statusBarContentColor: '#ffffff',
          navigationBarContentColor: '#ffffff'
        };
        windowClass.setWindowSystemBarProperties(SystemBarProperties);
      })
    });
  }

  onWindowStageDestroy(): void {
    // Main window is destroyed, release UI related resources
    hilog.info(0x0000, 'testTag', '%{public}s', 'Ability onWindowStageDestroy');
  }

  onForeground(): void {
    // Ability has brought to foreground
    hilog.info(0x0000, 'testTag', '%{public}s', 'Ability onForeground');
  }

  onBackground(): void {
    // Ability has back to background
    hilog.info(0x0000, 'testTag', '%{public}s', 'Ability onBackground');
  }
}
